/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    BookDetail: typeof import('./components/BookDetail.vue')['default']
    BookDetailDialog: typeof import('./components/BookDetailDialog.vue')['default']
    BookGrid: typeof import('./components/BookGrid.vue')['default']
    Button: typeof import('primevue/button')['default']
    CardCvvInputForm: typeof import('./components/CardCvvInputForm.vue')['default']
    CardDateInputForm: typeof import('./components/CardDateInputForm.vue')['default']
    CardInputForm: typeof import('./components/CardInputForm.vue')['default']
    CheckoutDetails: typeof import('./components/CheckoutDetails.vue')['default']
    CheckoutForm: typeof import('./components/CheckoutForm.vue')['default']
    CheckoutPage: typeof import('./components/CheckoutPage.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FormInputField: typeof import('./components/FormInputField.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    PageNotFound: typeof import('./components/PageNotFound.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    ShoppingCart: typeof import('./components/ShoppingCart.vue')['default']
    StarRating: typeof import('./components/StarRating.vue')['default']
  }
}
